export const NOW_PLAYING = "NOW_PLAYING";
export const APPEND_NOW_PLAYING = "APPEND_NOW_PLAYING";
export const POPULAR = "POPULAR";
export const TOP_RATED = "TOP_RATED";
export const SEARCHED_MOVIE = "SEARCHED_MOVIE";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const APPEND_SEARCH_MOVIE = "APPEND_SEARCH_MOVIE";
export const SEARCH_MOVIE_ERROR = "SEARCH_MOVIE_ERROR";
export const SEARCHED_MOVIE_NAV = "SEARCHED_MOVIE_NAV";

// actor types
export const POPULAR_ACTORS = "POPULAR_ACTORS";
export const SEARCH_ACTOR = "SEARCH_ACTOR";
export const ACTOR_INFO = "ACTOR_INFO";
export const APPEND_ACTORS_ACTRESSES = "APPEND_ACTORS_ACTRESSES";

// user types
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNOUT_USER = "SIGNOUT_USER";